// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppInfoService exposes read-only facts about the running binary.
 * 
 * It is its own service rather than a method on SettingsService because
 * SettingsService's contract is the single-row settings table. Platform facts
 * are not settings, and hanging them there is how every future "app fact"
 * would end up accumulating in the same place.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Platform reports the OS and architecture this binary was built for.
 */
export function Platform(): $CancellablePromise<$models.PlatformInfo> {
    return $Call.ByID(2823318317);
}
