// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ForwardService is bound to the frontend as ForwardService.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as forward$0 from "../forward/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Create validates the input and stores a new forward.
 */
export function Create($in: $models.ForwardInput): $CancellablePromise<domain$0.PortForward | null> {
    return $Call.ByID(3730213644, $in);
}

/**
 * Delete removes a saved forward definition.
 */
export function Delete(id: string): $CancellablePromise<void> {
    return $Call.ByID(772879475, id);
}

/**
 * List returns every forward saved for serverID.
 */
export function List(serverID: string): $CancellablePromise<domain$0.PortForward[] | null> {
    return $Call.ByID(2919896880, serverID);
}

/**
 * Start dials the forward's server (through its full jump chain, if any)
 * and starts the tunnel over that connection. Every step propagates its
 * error with its original code: an unknown forward or server is
 * ERR_NOT_FOUND, a bad jump chain is ERR_JUMP_CYCLE/ERR_JUMP_FAILED, a
 * dial failure keeps the dialer's classified code.
 * 
 * The already-running check happens BEFORE the dial, not after: dialing is
 * a full jump-chain SSH handshake, and Manager.Start's "already running"
 * branch never touches (let alone closes) conn — per its doc comment,
 * ownership only transfers to the Manager once Start actually accepts the
 * forward. Dialing first and then hitting that branch would leak the freshly
 * authenticated connection, since nothing would ever close it. Checking
 * Status first avoids the wasted dial entirely.
 * 
 * This has a benign TOCTOU: two concurrent Starts for the same id could both
 * pass the guard and both dial. That's acceptable for a single-user desktop
 * UI — the second one still fails, in mgr.Start, without leaking (see
 * below) — so no locking is added here for it.
 */
export function Start(id: string): $CancellablePromise<void> {
    return $Call.ByID(3482187924, id);
}

/**
 * Statuses lists every currently-running tunnel.
 */
export function Statuses(): $CancellablePromise<forward$0.Status[] | null> {
    return $Call.ByID(133285834);
}

/**
 * Stop tears the tunnel down. Stopping an id that isn't running is a no-op
 * (forward.Manager.Stop's contract).
 */
export function Stop(id: string): $CancellablePromise<void> {
    return $Call.ByID(1829380944, id);
}

/**
 * Update overwrites an existing forward's editable fields.
 */
export function Update($in: $models.ForwardInput): $CancellablePromise<domain$0.PortForward | null> {
    return $Call.ByID(1750888361, $in);
}
