// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * HealthService gathers live host metrics for the detail card. It opens its OWN
 * short-lived connection per probe and closes it — it never touches a terminal's
 * live connection, because opening a second channel on that connection tore the
 * session down on some servers ("unexpected packet in response to channel
 * open"). Probing is therefore explicit: the card runs it only on the Refresh
 * button, so the dial (and any 2FA/host-key prompt it triggers) is something the
 * user asked for.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Probe dials the server, runs its metric commands over the fresh connection,
 * and closes it. A dial failure (auth, host key, network) comes back as the
 * error, which the card shows; the metrics come from Linux /proc and POSIX df,
 * each best-effort.
 */
export function Probe(serverID: string): $CancellablePromise<$models.HealthReport> {
    return $Call.ByID(2782646247, serverID);
}
