// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * HealthService reads live host metrics over a connection the terminal already
 * holds — it never dials. All parsing is pure (below) and tested; only Probe
 * touches the network.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Probe gathers a server's health over a live connection, or reports Connected
 * false when there is none. The metrics come from Linux's /proc and POSIX df; a
 * host without them simply yields blank fields, not an error.
 */
export function Probe(serverID: string): $CancellablePromise<$models.HealthReport> {
    return $Call.ByID(2782646247, serverID);
}
