// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * HistoryService is the read side of the session log — the detail page's
 * "Recent sessions" card. The write side lives in SSHService, which records a
 * session's start and end; both share one store.SessionLogRepo.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";

/**
 * Recent returns a server's most recent sessions, newest first.
 */
export function Recent(serverID: string): $CancellablePromise<domain$0.SessionLog[] | null> {
    return $Call.ByID(4242957298, serverID);
}
