// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ImportService imports servers from ~/.ssh/config (FR-11).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Confirm imports the selected aliases (skipping any that are actually wildcard/
 * duplicate/invalid), then wires jump_id from ProxyJump. Returns the count
 * created.
 */
export function Confirm(aliases: string[] | null): $CancellablePromise<number> {
    return $Call.ByID(280105560, aliases);
}

/**
 * Preview parses the config and classifies each host: keep, or skip (wildcard /
 * duplicate / invalid). A missing config file is an empty preview, not an
 * error.
 */
export function Preview(): $CancellablePromise<$models.ImportPreview | null> {
    return $Call.ByID(4153298108);
}
