// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LocalService opens terminal sessions on the LOCAL machine — the app as a
 * plain terminal, with no server, no keychain and no host-key flow.
 * 
 * It owns Open only, on purpose: the session is registered in the same
 * term.Manager as every SSH session, so SSHService.Write / Resize / Close
 * already drive it by session id. That is deliberate reuse, not an oversight —
 * do not "fix" it by duplicating those three wrappers here.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Open starts a login shell on a local pty at cols x rows and returns the
 * session id the frontend subscribes term:data on, plus the shell's name (the
 * frontend picks a shell-integration snippet from it, exactly as it does for
 * the probed remote shell). No probe is needed — we launched the shell.
 */
export function Open(cols: number, rows: number): $CancellablePromise<$models.OpenResult> {
    return $Call.ByID(3183733390, cols, rows);
}
