// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LockService owns the app-lock PIN. The PIN is stored only as a bcrypt hash
 * in the Keychain (via secret.Store) — never in the DB, never in an event or
 * log. It is the layer the frontend calls to set, verify, change and remove
 * the PIN, and to factory-reset the app when the PIN is forgotten.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * ChangePin verifies the current PIN, then sets a new one.
 */
export function ChangePin(oldPin: string, newPin: string): $CancellablePromise<void> {
    return $Call.ByID(2630630749, oldPin, newPin);
}

/**
 * HasPin reports whether an app-lock PIN has been set.
 */
export function HasPin(): $CancellablePromise<boolean> {
    return $Call.ByID(1511923617);
}

/**
 * RemovePin verifies the current PIN, then deletes it (disables the lock's
 * ability to engage until a new PIN is set).
 */
export function RemovePin(current: string): $CancellablePromise<void> {
    return $Call.ByID(2467700237, current);
}

/**
 * ResetAll is the forgot-PIN escape hatch: it wipes app-owned data and returns
 * Zish to a clean first-run state WITHOUT uninstalling the app or touching
 * ~/.ssh. Mirrors UninstallService's Keychain-then-data order, but keeps the
 * process and DB alive. Honest by design: bypassing the lock costs your data.
 * 
 * Servers are removed with a single bulk DeleteAll rather than a per-id
 * Delete loop: the servers.jump_id self-foreign-key is NO ACTION, so deleting
 * a jump-host server one row at a time fails while another server still
 * references it. A bulk DELETE removes every row in one statement, so the
 * constraint is satisfied at statement end once nothing references anything.
 */
export function ResetAll(): $CancellablePromise<void> {
    return $Call.ByID(612650804);
}

/**
 * SetPin validates a six-digit PIN and stores its bcrypt hash.
 */
export function SetPin(pin: string): $CancellablePromise<void> {
    return $Call.ByID(3040299241, pin);
}

/**
 * VerifyPin reports whether pin matches the stored hash. A false with a nil
 * error means "wrong PIN"; a non-nil error means the Keychain read failed.
 */
export function VerifyPin(pin: string): $CancellablePromise<boolean> {
    return $Call.ByID(2044862290, pin);
}
