// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";

/**
 * CodeRequest is the code:request event payload (TZ 8 TOTP/2FA addendum).
 * It mirrors sshx.CodeRequest as a concrete named type so main.go's
 * application.RegisterEvent[CodeRequest] gives the binding generator a type
 * to turn into typed TypeScript. This file imports nothing from Wails, so
 * internal/service stays cgo-free.
 */
export interface CodeRequest {
    "requestID": string;
    "serverName": string;
    "prompt": string;

    /**
     * whether the typed answer should be visible
     */
    "echo": boolean;
}

/**
 * CreateServerInput is what the frontend sends to create or update a server.
 */
export interface CreateServerInput {
    "name": string;
    "host": string;
    "port": number;
    "user": string;
    "authType": domain$0.AuthType;
    "keyPath": string;

    /**
     * Password and Passphrase go to the OS keychain and NEVER into the
     * database (SEC-01). toServer() does not read them, so they cannot leak
     * into a domain.Server. An empty value means "do not write / leave
     * unchanged" (an agent server, or an edit that didn't touch the secret).
     */
    "password": string;
    "passphrase": string;

    /**
     * TOTPSecret, like Password/Passphrase, goes to the OS keychain and
     * NEVER into the database (SEC-01): toServer() does not read it, and
     * writeSecrets normalises/validates it through domain.ParseTOTPSecret
     * before storing. An empty value means "do not write / leave
     * unchanged" (same rule as Password). TwoFactor marks the server as
     * requiring a code at connect time and IS a normal row column (unlike
     * the secret itself) — see domain.Server.TwoFactor.
     */
    "totpSecret": string;
    "twoFactor": boolean;
    "jumpId": string | null;
    "group": string;
    "environment": domain$0.Environment;
    "tags": string[] | null;
    "notes": string;
}

/**
 * ForwardInput is what the frontend sends to create or update a saved port
 * forward. It mirrors CreateServerInput's shape: a plain JSON-tagged struct
 * the service turns into a domain.PortForward and validates again (SEC-08).
 */
export interface ForwardInput {
    "id": string;
    "serverId": string;
    "name": string;
    "type": domain$0.ForwardType;
    "bindAddr": string;
    "destHost": string;
    "bindPort": number;
    "destPort": number;
}

/**
 * HostKeyRequest is the hostkey:request event payload (TZ 8). It mirrors
 * sshx.HostKeyRequest as a concrete named type so main.go's
 * application.RegisterEvent[HostKeyRequest] gives the binding generator a
 * type to turn into typed TypeScript. This file imports nothing from Wails,
 * so internal/service stays cgo-free.
 */
export interface HostKeyRequest {
    "requestID": string;
    "hostname": string;
    "keyType": string;
    "fingerprint": string;
    "isChanged": boolean;
    "isRevoked": boolean;
    "oldFingerprint": string;
}

/**
 * ImportItem is one previewed host: a candidate server plus whether/why it is
 * skipped (FR-11.3 — skips are shown, not hidden).
 */
export interface ImportItem {
    "alias": string;
    "host": string;
    "user": string;
    "port": number;
    "authType": string;
    "keyPath": string;
    "proxyJump": string;
    "skip": boolean;
    "skipReason": string;
}

/**
 * ImportPreview is the whole preview: the source path and every host, keep and
 * skip alike.
 */
export interface ImportPreview {
    "path": string;
    "items": ImportItem[] | null;
}

/**
 * OpenResult is what both SSHService.Open and LocalService.Open hand the
 * frontend. Shell is the detected login shell ("bash"/"zsh"/"fish"), or "" when
 * it could not be classified — the frontend maps that to "inject nothing" and
 * reports it honestly in the status bar.
 */
export interface OpenResult {
    "sessionID": string;
    "shell": string;
}

/**
 * SftpProgress is the sftp:progress event payload: one update for an in-flight
 * transfer (or its terminal Finished/Error state). Carries no secret (SEC-01).
 */
export interface SftpProgress {
    "transferID": string;

    /**
     * "upload" | "download"
     */
    "direction": string;
    "currentFile": string;
    "done": number;
    "total": number;
    "finished": boolean;

    /**
     * non-empty on failure
     */
    "error": string;
}

/**
 * SnippetInput is what the frontend sends to create or update a saved
 * snippet. It mirrors ForwardInput's shape: a plain JSON-tagged struct the
 * service turns into a domain.Snippet and validates again (SEC-08).
 */
export interface SnippetInput {
    "id": string;
    "name": string;
    "body": string;
    "scope": domain$0.SnippetScope;
    "scopeRef": string;
    "slot": number;
}

/**
 * TOTPCodeView is one server's current verification code for the authenticator
 * panel. It carries the DERIVED code only — never the secret (SEC-01).
 */
export interface TOTPCodeView {
    "serverId": string;
    "serverName": string;

    /**
     * 6 digits
     */
    "code": string;

    /**
     * seconds until the 30s window rolls (1..30)
     */
    "expiresIn": number;
}

/**
 * TestResult is the outcome of TestConnection (FR-04). A connection outcome
 * (refused, timed out, auth failed, host key declined, keychain locked) is a
 * normal OK:false result carrying Code — not a thrown error — so the
 * frontend's result strip can render the TZ 11.2 message for that code.
 */
export interface TestResult {
    "ok": boolean;
    "latencyMs": number;
    "banner": string;

    /**
     * TZ 7.1 extension: the ERR_ code on failure, "" on success
     */
    "code": string;
    "error": string;
}

/**
 * TrayConnect is the tray:connect event payload: the id of the pinned server
 * whose menu-bar entry was clicked. main.go emits it (after showing the window)
 * and the frontend opens or focuses that server. Named here — like
 * HostKeyRequest/CodeRequest — so main.go's application.RegisterEvent[TrayConnect]
 * gives the binding generator a type for typed TypeScript, while
 * internal/service stays cgo-free.
 */
export interface TrayConnect {
    "serverID": string;
}
