// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ServerService is bound to the frontend as ServerService.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sshx$0 from "../sshx/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Create validates the input and stores a new server.
 */
export function Create(input: $models.CreateServerInput): $CancellablePromise<domain$0.Server | null> {
    return $Call.ByID(563937078, input);
}

/**
 * Delete removes a server and its keychain secrets (FR-01.3, FR-03.4).
 */
export function Delete(id: string): $CancellablePromise<void> {
    return $Call.ByID(802376765, id);
}

/**
 * DetectKeys lists likely private keys in ~/.ssh (FR-02.5).
 */
export function DetectKeys(): $CancellablePromise<sshx$0.KeyInfo[] | null> {
    return $Call.ByID(294771405);
}

/**
 * Duplicate copies a server under the name "{name} copy" (FR-01.4).
 */
export function Duplicate(id: string): $CancellablePromise<domain$0.Server | null> {
    return $Call.ByID(1843946899, id);
}

/**
 * ExportJSON writes all servers as JSON to path (FR-12 Data). Secrets stay in
 * the keychain; only server profiles are written.
 */
export function ExportJSON(path: string): $CancellablePromise<void> {
    return $Call.ByID(3763069010, path);
}

/**
 * Get returns one server by ID.
 */
export function Get(id: string): $CancellablePromise<domain$0.Server | null> {
    return $Call.ByID(1674858990, id);
}

/**
 * Groups returns the distinct group names in use, for the sidebar headers.
 */
export function Groups(): $CancellablePromise<string[] | null> {
    return $Call.ByID(2853674962);
}

/**
 * ImportJSON reads a server-JSON file, validates every entry (SEC-07), skips
 * duplicates (same host/port/user) — both against servers already in the
 * database and against ones created earlier in this same import — and
 * creates the rest. Returns the count created.
 */
export function ImportJSON(path: string): $CancellablePromise<number> {
    return $Call.ByID(3445467517, path);
}

/**
 * List returns every server, ordered for the sidebar.
 */
export function List(): $CancellablePromise<domain$0.Server[] | null> {
    return $Call.ByID(3860109822);
}

/**
 * SSHCommand renders the openssh equivalent for the clipboard (FR-01.9).
 */
export function SSHCommand(id: string): $CancellablePromise<string> {
    return $Call.ByID(2757781409, id);
}

/**
 * TestConnection opens a connection to verify the server works (FR-04),
 * running the full host-key flow, then closes it. A connection outcome
 * (refused, auth failed, host key declined, keychain locked) is a normal
 * failed TestResult; only a missing server id is a thrown error.
 * 
 * No ctx timeout is imposed here — the dialer owns the whole connect
 * ceiling via its own handshakeDeadline (internal/sshx.Dialer), which is
 * deliberately longer than the network-only FR-04.3 timeout (that one now
 * lives as the dialer's dialTimeout, configurable in v0.5) so a legitimate
 * host-key prompt (up to 60s) is never killed mid-decision. A ctx timeout
 * here would re-impose a second, shorter ceiling on top of that one.
 */
export function TestConnection(id: string): $CancellablePromise<$models.TestResult | null> {
    return $Call.ByID(976953638, id);
}

/**
 * Update overwrites an existing server's editable fields.
 * 
 * This is a full replace of the FORM fields, not a patch. Usage state
 * (last_used_at, use_count, sort_order) is intentionally NOT written by
 * Update — the repository's updatableColumns excludes it, and BumpUsage
 * owns it — so the form can no longer clobber a connection bump. CreatedAt
 * is carried over defensively (it is not in updatableColumns either).
 */
export function Update(id: string, input: $models.CreateServerInput): $CancellablePromise<domain$0.Server | null> {
    return $Call.ByID(2665495899, id, input);
}
