// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SessionStateService is the frontend's door to the persisted open-tab list
 * behind "Restore sessions on launch". The frontend saves the list as tabs open
 * and close, and loads it once at launch.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * LoadOpenTabs returns the server ids to reopen at launch.
 */
export function LoadOpenTabs(): $CancellablePromise<string[] | null> {
    return $Call.ByID(1110940860);
}

/**
 * SaveOpenTabs records the server ids of the currently open terminal tabs.
 */
export function SaveOpenTabs(serverIDs: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(2976476957, serverIDs);
}
