// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService is bound to the frontend as SettingsService.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";

/**
 * Get returns the current settings, sanitised.
 */
export function Get(): $CancellablePromise<domain$0.Settings | null> {
    return $Call.ByID(1774610284);
}

/**
 * Update sanitises and stores the settings, and applies the start-at-login side
 * effect when that flag changed. A login-agent failure is surfaced (the user
 * asked for it) but the settings row is still saved first.
 */
export function Update($in: domain$0.Settings): $CancellablePromise<domain$0.Settings | null> {
    return $Call.ByID(697474513, $in);
}
