// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SftpService opens per-server SFTP sessions over the shared dialer and runs
 * file transfers, emitting sftp:progress. Its own view (frontend) is separate
 * from terminal sessions.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sftpx$0 from "../sftpx/models.js";

/**
 * CancelTransfer aborts an in-flight transfer.
 */
export function CancelTransfer(transferID: string): $CancellablePromise<void> {
    return $Call.ByID(3021136541, transferID);
}

/**
 * Close ends an SFTP session and its SSH connection.
 */
export function Close(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(1352819560, sessionID);
}

/**
 * CreateFile creates a new empty file on the remote side ("New file…").
 */
export function CreateFile(sessionID: string, path: string): $CancellablePromise<void> {
    return $Call.ByID(389766934, sessionID, path);
}

/**
 * CreateLocalFile creates a new empty local file ("New file…").
 */
export function CreateLocalFile(path: string): $CancellablePromise<void> {
    return $Call.ByID(1992894325, path);
}

/**
 * Download is Upload's mirror: remotePath -> localDir.
 */
export function Download(sessionID: string, remotePath: string, localDir: string): $CancellablePromise<string> {
    return $Call.ByID(728268348, sessionID, remotePath, localDir);
}

/**
 * ListLocal needs no session — the left pane is the local FS.
 */
export function ListLocal(dir: string): $CancellablePromise<sftpx$0.FileEntry[] | null> {
    return $Call.ByID(1018153767, dir);
}

/**
 * ListRemote lists dir on the remote side of an open SFTP session.
 */
export function ListRemote(sessionID: string, dir: string): $CancellablePromise<sftpx$0.FileEntry[] | null> {
    return $Call.ByID(391647578, sessionID, dir);
}

/**
 * LocalHome needs no session — the left pane is the local FS.
 */
export function LocalHome(): $CancellablePromise<string> {
    return $Call.ByID(1380931764);
}

/**
 * Mkdir creates a directory on the remote side of an open SFTP session.
 */
export function Mkdir(sessionID: string, path: string): $CancellablePromise<void> {
    return $Call.ByID(3410111815, sessionID, path);
}

/**
 * MkdirLocal creates a directory on the local side.
 */
export function MkdirLocal(path: string): $CancellablePromise<void> {
    return $Call.ByID(594946854, path);
}

/**
 * Open dials serverID (reusing the auth/keychain/host-key/TOTP path), starts an
 * SFTP session, and returns its id. Mirrors SSHService.Open's dial+zero.
 */
export function Open(serverID: string): $CancellablePromise<string> {
    return $Call.ByID(1783408244, serverID);
}

/**
 * ReadFile returns a remote text file's contents for the editor.
 */
export function ReadFile(sessionID: string, path: string): $CancellablePromise<string> {
    return $Call.ByID(792451486, sessionID, path);
}

/**
 * ReadLocalFile / WriteLocalFile edit the left pane's local files — no session.
 */
export function ReadLocalFile(path: string): $CancellablePromise<string> {
    return $Call.ByID(1840372029, path);
}

/**
 * RemoteHome is the session's initial remote directory.
 */
export function RemoteHome(sessionID: string): $CancellablePromise<string> {
    return $Call.ByID(2176337805, sessionID);
}

/**
 * Remove deletes a remote file, or a directory and everything under it.
 */
export function Remove(sessionID: string, path: string): $CancellablePromise<void> {
    return $Call.ByID(4091168772, sessionID, path);
}

/**
 * RemoveLocal deletes a local file, or a directory and everything under it.
 */
export function RemoveLocal(path: string): $CancellablePromise<void> {
    return $Call.ByID(1639093039, path);
}

/**
 * Rename moves/renames a remote path.
 */
export function Rename(sessionID: string, oldPath: string, newPath: string): $CancellablePromise<void> {
    return $Call.ByID(2826446262, sessionID, oldPath, newPath);
}

/**
 * RenameLocal renames a local path (refusing to overwrite an existing target).
 */
export function RenameLocal(oldPath: string, newPath: string): $CancellablePromise<void> {
    return $Call.ByID(3081926909, oldPath, newPath);
}

/**
 * Upload streams localPath to remoteDir on the session and returns a transferID
 * immediately; the copy runs in a goroutine, emitting sftp:progress as it goes
 * and a terminal Finished (with Error, if any). CancelTransfer(transferID) aborts it.
 */
export function Upload(sessionID: string, localPath: string, remoteDir: string): $CancellablePromise<string> {
    return $Call.ByID(779034325, sessionID, localPath, remoteDir);
}

/**
 * WriteFile replaces a remote file's contents from the editor (atomic).
 */
export function WriteFile(sessionID: string, path: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(1980766301, sessionID, path, content);
}

/**
 * WriteLocalFile replaces a local file's contents from the editor (atomic).
 */
export function WriteLocalFile(path: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(481025428, path, content);
}
