// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SnippetService is bound to the frontend as SnippetService. Unlike
 * ForwardService it needs no secret store, dialer, or session manager: a
 * snippet carries no secret (SEC-01) and does nothing on its own — a
 * terminal runs its Body as ordinary keystrokes via SSHService.Write.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ApplicableTo returns every snippet that applies to a terminal for
 * serverID in groupName (global + matching group + matching server).
 */
export function ApplicableTo(serverID: string, groupName: string): $CancellablePromise<domain$0.Snippet[] | null> {
    return $Call.ByID(135292072, serverID, groupName);
}

/**
 * BySlot returns the applicable snippet bound to slot for a terminal's
 * server/group, or domain.ErrNotFound when none matches.
 * 
 * Slot 0 means "no slot" (domain.Snippet.Slot's own doc: "0=none, 1..9
 * quick-run") — a snippet stored with Slot 0 simply isn't offered on any
 * ⌘1-9 quick-run key, so there is no key that could ever produce
 * BySlot(0, …) from the UI. Rather than let that call silently match the
 * first unslotted-but-otherwise-applicable snippet it happens to find,
 * BySlot treats any slot outside 1..9 as an automatic non-match: it's the
 * same "no such quick-run slot" answer a caller gets for any other slot with
 * nothing bound to it.
 */
export function BySlot(slot: number, serverID: string, groupName: string): $CancellablePromise<domain$0.Snippet | null> {
    return $Call.ByID(534079469, slot, serverID, groupName);
}

/**
 * Create validates the input and stores a new snippet.
 */
export function Create($in: $models.SnippetInput): $CancellablePromise<domain$0.Snippet | null> {
    return $Call.ByID(3008608632, $in);
}

/**
 * Delete removes a saved snippet definition.
 */
export function Delete(id: string): $CancellablePromise<void> {
    return $Call.ByID(4030624039, id);
}

/**
 * List returns every saved snippet (the management view's unfiltered
 * catalog — see SnippetRepo.List).
 */
export function List(): $CancellablePromise<domain$0.Snippet[] | null> {
    return $Call.ByID(454040948);
}

/**
 * Update overwrites an existing snippet's editable fields.
 */
export function Update($in: $models.SnippetInput): $CancellablePromise<domain$0.Snippet | null> {
    return $Call.ByID(436208173, $in);
}
