// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SSHService is bound to the frontend. It owns host-key confirmation (v0.2)
 * and, from v0.3, the terminal session lifecycle: Open dials + starts a PTY +
 * registers it with the term.Manager; Write/Resize/Close delegate to it.
 * 
 * Write/Resize/Close are keyed purely by session id in the shared
 * term.Manager, so they also drive sessions opened by LocalService.Open —
 * not just ones opened by SSHService.Open. Anything added here that assumes
 * a server-scoped session (e.g. looking up a Server row by session id) would
 * break local panes.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Broadcast writes the same base64 payload to every listed session (FR-15). It
 * is best-effort: a write to a gone session doesn't stop the others; the first
 * error is returned so the UI can surface a partial failure.
 */
export function Broadcast(sessionIDs: string[] | null, dataB64: string): $CancellablePromise<void> {
    return $Call.ByID(1722845442, sessionIDs, dataB64);
}

/**
 * Close ends a session at the user's request (closing a pane/tab).
 */
export function Close(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(3151145289, sessionID);
}

/**
 * ConfirmHostKey delivers the user's decision for a pending host-key prompt.
 * The blocking Test/Open dial is waiting on this.
 */
export function ConfirmHostKey(requestID: string, accept: boolean): $CancellablePromise<void> {
    return $Call.ByID(1546755590, requestID, accept);
}

/**
 * Open connects to a server and starts an interactive PTY, returning an
 * OpenResult carrying the new session id the frontend subscribes term:data
 * on and the detected login shell. It runs the full host-key flow (a
 * hostkey:request may fire mid-dial, exactly as in TestConnection). The pty
 * is opened at cols x rows — the frontend's already-fitted xterm size — so a
 * long-output command scrolls correctly from the first frame instead of
 * overwriting until the next resize. cols/rows under 1 (an unmeasured
 * caller) fall back to a sane 80x24 inside OpenSession. The frontend still
 * issues a Resize on every later container resize.
 * 
 * No ctx timeout on the dial itself — the dialer owns the whole connect
 * ceiling via its handshakeDeadline, deliberately longer than the network
 * timeout so a legitimate host-key prompt is never killed mid-decision (same
 * reasoning as TestConnection). That ceiling is not the whole story anymore,
 * though: when the probe below runs, sshx.DetectShell adds its own
 * independent ~3s timeout on top of the already-established connection, so a
 * hung host can delay a successful Open by up to that long beyond the dial.
 */
export function Open(serverID: string, cols: number, rows: number): $CancellablePromise<$models.OpenResult> {
    return $Call.ByID(4190982559, serverID, cols, rows);
}

/**
 * Resize forwards the terminal's new (cols, rows) to the session's pty —
 * remote (SSH) or local, whichever this session id was opened as.
 */
export function Resize(sessionID: string, cols: number, rows: number): $CancellablePromise<void> {
    return $Call.ByID(3429379467, sessionID, cols, rows);
}

/**
 * SetConnRegistry wires the live-connection registry the Health card reads.
 * Package-level wiring (like SetForwardDeps) rather than a constructor arg, so
 * the many existing SSHService call sites keep their signature; a nil registry
 * (tests) simply means sessions are not tracked for reuse.
 */
export function SetConnRegistry(r: $models.ConnRegistry | null): $CancellablePromise<void> {
    return $Call.ByID(1045466036, r);
}

/**
 * SubmitCode delivers the user's typed 2FA code for a pending code:request
 * (TOTP or an unrecognised keyboard-interactive question). The blocking
 * Open dial — inside the keyboard-interactive challenge — is waiting on
 * this.
 */
export function SubmitCode(requestID: string, code: string): $CancellablePromise<void> {
    return $Call.ByID(1188862842, requestID, code);
}

/**
 * Write sends base64-encoded input to a session's shell.
 */
export function Write(sessionID: string, dataB64: string): $CancellablePromise<void> {
    return $Call.ByID(915674246, sessionID, dataB64);
}
