// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SSHService is bound to the frontend. It owns host-key confirmation (v0.2)
 * and, from v0.3, the terminal session lifecycle: Open dials + starts a PTY +
 * registers it with the term.Manager; Write/Resize/Close delegate to it.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * Broadcast writes the same base64 payload to every listed session (FR-15). It
 * is best-effort: a write to a gone session doesn't stop the others; the first
 * error is returned so the UI can surface a partial failure.
 */
export function Broadcast(sessionIDs: string[] | null, dataB64: string): $CancellablePromise<void> {
    return $Call.ByID(1722845442, sessionIDs, dataB64);
}

/**
 * Close ends a session at the user's request (closing a pane/tab).
 */
export function Close(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(3151145289, sessionID);
}

/**
 * ConfirmHostKey delivers the user's decision for a pending host-key prompt.
 * The blocking Test/Open dial is waiting on this.
 */
export function ConfirmHostKey(requestID: string, accept: boolean): $CancellablePromise<void> {
    return $Call.ByID(1546755590, requestID, accept);
}

/**
 * Open connects to a server and starts an interactive PTY, returning the new
 * session id the frontend subscribes term:data on. It runs the full host-key
 * flow (a hostkey:request may fire mid-dial, exactly as in TestConnection).
 * The pty is opened at cols x rows — the frontend's already-fitted xterm
 * size — so a long-output command scrolls correctly from the first frame
 * instead of overwriting until the next resize. cols/rows under 1 (an
 * unmeasured caller) fall back to a sane 80x24 inside OpenSession. The
 * frontend still issues a Resize on every later container resize.
 * 
 * No ctx timeout here — the dialer owns the whole connect ceiling via its
 * handshakeDeadline, deliberately longer than the network timeout so a
 * legitimate host-key prompt is never killed mid-decision (same reasoning as
 * TestConnection).
 */
export function Open(serverID: string, cols: number, rows: number): $CancellablePromise<string> {
    return $Call.ByID(4190982559, serverID, cols, rows);
}

/**
 * Resize forwards the terminal's new (cols, rows) to the remote pty.
 */
export function Resize(sessionID: string, cols: number, rows: number): $CancellablePromise<void> {
    return $Call.ByID(3429379467, sessionID, cols, rows);
}

/**
 * Write sends base64-encoded input to a session's shell.
 */
export function Write(sessionID: string, dataB64: string): $CancellablePromise<void> {
    return $Call.ByID(915674246, sessionID, dataB64);
}
