// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UninstallService removes every app-owned artifact and then trashes the app.
 * dataDir/logDir are injected (not read from platform here) so tests point them
 * at temp dirs and never touch the developer's real data.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * Uninstall removes app-owned data — Keychain secrets, the start-at-login
 * agent, the data and log directories — then moves the app bundle to the Trash
 * and asks the app to quit. It never touches ~/.ssh. Every removal is
 * best-effort (one failure must not strand the rest — the app is about to be
 * gone). If the bundle can't be trashed the data is still gone, so it returns
 * that error WITHOUT quitting, letting the UI tell the user to trash the app by
 * hand. On full success it fires onUninstalled (quit) and returns nil.
 */
export function Uninstall(): $CancellablePromise<void> {
    return $Call.ByID(3331619939);
}
