// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FileEntry is one directory entry, local or remote. Mode is the 9-char
 * permission string (os.FileMode.String()'s tail, e.g. "-rw-r--r--").
 */
export interface FileEntry {
    "name": string;
    "isDir": boolean;
    "size": number;
    "mode": string;
    "modTime": string;
}
