// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as service$0 from "../../../../salawat/sshmgr/internal/service/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as term$0 from "../../../../salawat/sshmgr/internal/term/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "hostkey:request": service$0.HostKeyRequest;
            "session:state": term$0.State;
            "term:data": term$0.Output;
        }
    }
}
