// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * State is a forward's lifecycle state.
 */
export enum State {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * The three states a forward can report: running while its listener is
     * accepting, stopped after a deliberate Stop, error when the listener failed
     * to bind or the accept loop died unexpectedly.
     */
    StateRunning = "running",
    StateStopped = "stopped",
    StateError = "error",
};

/**
 * Status is a snapshot of one forward's state, suitable for emitting to the
 * frontend or returning from Status/Running.
 */
export interface Status {
    "forwardId": string;
    "state": State;
    "detail": string;
}
