// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AuthType is how a connection authenticates.
 */
export enum AuthType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * The supported authentication methods. v0.1 only ever writes AuthAgent —
     * it is the one method that needs no secret, and secrets wait for the
     * keychain (SEC-01).
     */
    AuthPassword = "password",
    AuthKey = "key",
    AuthAgent = "agent",
};

/**
 * Environment tags a server with the blast radius of getting it wrong. It
 * drives the UI-11 marker and, from v1, the production guard (FR-14).
 */
export enum Environment {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * The environments a server can be tagged with. EnvNone is the default:
     * untagged, not "safe".
     */
    EnvProd = "prod",
    EnvStaging = "staging",
    EnvDev = "dev",
    EnvNone = "none",
};

/**
 * ForwardType is the tunnel direction. L = local (-L), R = remote (-R).
 */
export enum ForwardType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * The tunnel directions. ForwardLocal is an -L forward (local port to a remote
     * destination); ForwardRemote is an -R forward (remote port to a local one).
     */
    ForwardLocal = "L",
    ForwardRemote = "R",
};

/**
 * PortForward is a saved tunnel definition attached to a server. It carries no
 * secret (SEC-01) — it only names ports and hosts.
 */
export interface PortForward {
    "id": string;
    "serverId": string;
    "name": string;
    "type": ForwardType;
    "bindAddr": string;
    "bindPort": number;
    "destHost": string;
    "destPort": number;
    "createdAt": string;
    "updatedAt": string;
}

/**
 * Server is a connection profile.
 * 
 * It carries no password or passphrase field, and must never grow one:
 * secrets live in the OS keychain only (SEC-01).
 */
export interface Server {
    "id": string;
    "name": string;
    "host": string;
    "port": number;
    "user": string;
    "authType": AuthType;
    "keyPath": string;
    "jumpId": string | null;
    "group": string;
    "environment": Environment;
    "tags": string;
    "notes": string;
    "lastUsedAt": string | null;
    "useCount": number;
    "sortOrder": number;
    "createdAt": string;
    "updatedAt": string;
}

/**
 * Settings is the single-row app configuration table (FR-12.1: settings live
 * in the database, never localStorage). ID is always 1. Defaults come from
 * DefaultSettings() and the gorm column defaults, applied on first run.
 */
export interface Settings {
    /**
     * General
     */
    "startAtLogin": boolean;
    "keepRunningInTray": boolean;
    "confirmOnQuit": boolean;

    /**
     * ProdConfirm is persisted now; enforcement (the prod guard, FR-14) is v0.7.
     */
    "prodConfirm": boolean;
    "connectTimeoutSecs": number;

    /**
     * Terminal (read live by the frontend; v0.3 hard-coded these)
     */
    "termFont": string;
    "termFontSize": number;
    "termTheme": string;

    /**
     * block|bar|underline
     */
    "termCursor": string;
    "termBlink": boolean;
    "termScrollback": number;
}
