// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AuthType is how a connection authenticates.
 */
export enum AuthType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * The supported authentication methods. v0.1 only ever writes AuthAgent —
     * it is the one method that needs no secret, and secrets wait for the
     * keychain (SEC-01).
     */
    AuthPassword = "password",
    AuthKey = "key",
    AuthAgent = "agent",
};

/**
 * Environment tags a server with the blast radius of getting it wrong. It
 * drives the UI-11 marker and, from v1, the production guard (FR-14).
 */
export enum Environment {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * The environments a server can be tagged with. EnvNone is the default:
     * untagged, not "safe".
     */
    EnvProd = "prod",
    EnvStaging = "staging",
    EnvDev = "dev",
    EnvNone = "none",
};

/**
 * ForwardType is the tunnel direction. L = local (-L), R = remote (-R), D =
 * dynamic (-D, a SOCKS5 proxy).
 */
export enum ForwardType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * The tunnel directions. ForwardLocal is an -L forward (local port to a
     * remote destination); ForwardRemote is an -R forward (remote port to a
     * local one); ForwardDynamic is a -D forward (a local SOCKS5 proxy port —
     * each proxied connection's destination is negotiated by the SOCKS client
     * per-connection rather than fixed at forward-creation time, so it carries
     * no DestHost/DestPort).
     */
    ForwardLocal = "L",
    ForwardRemote = "R",
    ForwardDynamic = "D",
};

/**
 * PortForward is a saved tunnel definition attached to a server. It carries no
 * secret (SEC-01) — it only names ports and hosts.
 */
export interface PortForward {
    "id": string;
    "serverId": string;
    "name": string;
    "type": ForwardType;
    "bindAddr": string;
    "bindPort": number;
    "destHost": string;
    "destPort": number;
    "createdAt": string;
    "updatedAt": string;
}

/**
 * Server is a connection profile.
 * 
 * It carries no password or passphrase field, and must never grow one:
 * secrets live in the OS keychain only (SEC-01).
 */
export interface Server {
    "id": string;
    "name": string;
    "host": string;
    "port": number;
    "user": string;
    "authType": AuthType;
    "keyPath": string;
    "jumpId": string | null;
    "group": string;
    "environment": Environment;
    "tags": string;
    "notes": string;

    /**
     * TwoFactor marks a server as requiring a TOTP code at connect time.
     * The code and its secret NEVER live here or anywhere in the DB/JSON
     * export — only this flag does. The secret itself lives in the OS
     * keychain (SEC-01), keyed by this server's ID (secret.Store).
     */
    "twoFactor": boolean;

    /**
     * Pinned marks a server for the menu-bar tray's quick-connect list. Not a
     * secret; capped at 5 pins by the service, never written by a form Update
     * (updatableColumns excludes it) — only by ServerService.SetPinned.
     */
    "pinned": boolean;
    "lastUsedAt": string | null;
    "useCount": number;
    "sortOrder": number;
    "createdAt": string;
    "updatedAt": string;
}

/**
 * Settings is the single-row app configuration table (FR-12.1: settings live
 * in the database, never localStorage). ID is always 1. Defaults come from
 * DefaultSettings() and the gorm column defaults, applied on first run.
 */
export interface Settings {
    /**
     * General
     */
    "startAtLogin": boolean;
    "keepRunningInTray": boolean;
    "confirmOnQuit": boolean;
    "connectTimeoutSecs": number;

    /**
     * Terminal (read live by the frontend; v0.3 hard-coded these)
     */
    "termFont": string;
    "termFontSize": number;
    "termTheme": string;

    /**
     * block|bar|underline
     */
    "termCursor": string;
    "termBlink": boolean;
    "termScrollback": number;

    /**
     * ShellIntegration injects an OSC 133 snippet on connect for a detected
     * bash, zsh, or fish login shell, to mark prompt/command/output
     * boundaries. Any other detected shell gets no snippet — the status bar
     * reports that outcome rather than staying silent about it. Off = plain
     * terminal, no detection probe.
     */
    "shellIntegration": boolean;

    /**
     * Prod guard (FR-14): an ERGONOMIC barrier on dangerous commands typed
     * against a prod-tagged server, not a security control (FR-14.9). The DB
     * default for GuardPatterns is deliberately empty (multi-line text doesn't
     * fit a single-line gorm default); the real default list lives in
     * DefaultSettings() below and is what every first-run row actually gets.
     */
    "guardEnabled": boolean;
    "guardPatterns": string;

    /**
     * GuardPatternsLocal is the guard list for the LOCAL terminal tab. It is
     * separate from (and shorter than) GuardPatterns on purpose: `rm -rf` as a
     * substring is an everyday command on a dev machine, and a barrier that
     * fires on every `rm -rf node_modules` gets switched off — which would also
     * disarm the production one. Same DB-default caveat as GuardPatterns: the
     * real first-run list lives in DefaultSettings().
     */
    "guardPatternsLocal": string;

    /**
     * TourSeen is set true once the first-run welcome tour has been shown (or
     * skipped); false on a fresh install so the tour auto-opens exactly once.
     * Not a secret — a plain onboarding flag.
     */
    "tourSeen": boolean;
}

/**
 * Snippet is a saved command a user can run against a server's terminal. It
 * carries no secret (SEC-01) — just a name, a body, and where it applies.
 */
export interface Snippet {
    "id": string;
    "name": string;
    "body": string;
    "scope": SnippetScope;

    /**
     * group name (group scope) / server id (server scope); "" for global
     */
    "scopeRef": string;

    /**
     * 0=none, 1..9 quick-run
     */
    "slot": number;
    "createdAt": string;
    "updatedAt": string;
}

/**
 * SnippetScope controls which servers a snippet is offered for: everywhere,
 * one group, or one server.
 */
export enum SnippetScope {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * The valid snippet scopes.
     */
    ScopeGlobal = "global",
    ScopeGroup = "group",
    ScopeServer = "server",
};
