// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BiometricService exposes macOS Touch ID to the frontend. It lives in package
 * main because it needs cgo, which the project keeps out of internal/.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * Authenticate presents the Touch ID prompt and blocks until the user
 * responds. Returns true on success. On success the frontend simply unlocks —
 * Touch ID is a convenience gate over the mandatory PIN.
 */
export function Authenticate(reason: string): $CancellablePromise<boolean> {
    return $Call.ByID(2487597414, reason);
}

/**
 * Available reports whether Touch ID can be used to unlock. Gated on running
 * from a packaged .app: an unsigned `wails3 dev` binary cannot present the
 * LocalAuthentication prompt, so we report false there and the UI falls back
 * to PIN-only rather than showing a Touch ID button that always fails.
 */
export function Available(): $CancellablePromise<boolean> {
    return $Call.ByID(1136962446);
}
