// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DataService is bound to the frontend for the FR-12 Data section. It lives in
 * package main because the native file dialogs need Wails' application (cgo-
 * gated, must not enter internal/). The actual JSON/validate/backup logic
 * stays in the cgo-free service layer; this only drives the dialogs.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * BackupDatabase prompts for a save path and writes a consistent copy of the
 * SQLite database there via VACUUM INTO (WAL-safe; see service.BackupDatabase).
 */
export function BackupDatabase(): $CancellablePromise<void> {
    return $Call.ByID(847448042);
}

/**
 * ExportServers prompts for a save path and writes the server JSON there.
 */
export function ExportServers(): $CancellablePromise<void> {
    return $Call.ByID(3629683449);
}

/**
 * ImportServers prompts for a JSON file and imports it, returning the count.
 */
export function ImportServers(): $CancellablePromise<number> {
    return $Call.ByID(2401461356);
}

/**
 * RevealDataFolder opens the app's data folder in the OS file manager.
 */
export function RevealDataFolder(): $CancellablePromise<void> {
    return $Call.ByID(1560959260);
}
