// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * EditService exposes the platform's own edit actions to the frontend.
 * 
 * It lives in package main because it needs cgo, which this project keeps out
 * of internal/ entirely (the gate builds internal/... with CGO_ENABLED=0).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * Paste performs AppKit's standard paste: action.
 * 
 * The terminal's right-click Paste calls this instead of reading the clipboard
 * itself: since macOS 15 a programmatic NSPasteboard read is gated behind a
 * confirmation button the user has to click, while a real paste command
 * travelling the responder chain is not. Cmd+V needs none of this — WebKit
 * already handles that natively.
 */
export function Paste(): $CancellablePromise<void> {
    return $Call.ByID(1231005132);
}
