// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as BiometricService from "./biometricservice.js";
import * as DataService from "./dataservice.js";
import * as EditService from "./editservice.js";
export {
    BiometricService,
    DataService,
    EditService
};
