// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Output is the term:data payload. Data is base64 so arbitrary (non-UTF-8)
 * terminal bytes survive JSON marshalling intact.
 */
export interface Output {
    "sessionID": string;
    "seq": number;
    "data": string;
}

/**
 * State is the session:state payload. State is connected|closed; Code/Message
 * are set only on an abnormal close (drop / dead peer).
 */
export interface State {
    "sessionID": string;
    "state": string;
    "code": string;
    "message": string;
}
