// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * KeyInfo describes a private key found on disk. It never carries key
 * material — only metadata safe to hand to the frontend.
 */
export interface KeyInfo {
    "path": string;

    /**
     * ed25519, rsa, ecdsa
     */
    "type": string;
    "encrypted": boolean;
}
